# Oh My Zsh
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="agnoster" # https://github.com/agnoster/agnoster-zsh-theme

HYPHEN_INSENSITIVE="true"
DISABLE_UPDATE_PROMPT="true"
ENABLE_CORRECTION="true"
HIST_STAMPS="mm/dd/yyyy"

# Plugins (no need to manually source plugin files)
plugins=(
    git
    z
    zsh-autosuggestions
    dirhistory
    history
    web-search
    fzf
    zsh-fzf-history-search
    zsh-syntax-highlighting
)

# Hide username when it's you
DEFAULT_USER="${USER}"

source "$ZSH/oh-my-zsh.sh"

# Prompt tweak (agnoster)
prompt_context() {
    prompt_segment orange default "%(!.%{%F{yellow}%}.)🚀"
}

prompt_end() {
    if [[ -n $CURRENT_BG ]]; then
        print -n "%{%k%F{$CURRENT_BG}%}$SEGMENT_SEPARATOR"
    else
        print -n "%{%k%}"
    fi
    print -n "%{%f%}"
    CURRENT_BG=''
    printf "\n ➜"
}

prompt_virtualenv() {
    # if [[ -n $CONDA_DEFAULT_ENV && -z $CONDA_ENV_DISABLE_PROMPT ]]; then
    #     # You can execute this command to disable conda native prompt.
    #     # `conda config --set changeps1 False`
    
    #     # local conda_prompt_prefix=${CONDA_PROMPT_PREFIX:-"🐍 "}
    #     local conda_prompt_prefix="$CONDA_PROMPT_PREFIX"
    #     # local conda_prompt_prefix="$CONDA_PROMPT_PREFIX"
    #     prompt_segment "$AGNOSTER_CONDA_BG" "$AGNOSTER_CONDA_FG" "$conda_prompt_prefix$CONDA_DEFAULT_ENV"
    # fi
    
    # if [[ -n "$VIRTUAL_ENV" && -n "$VIRTUAL_ENV_DISABLE_PROMPT" ]]; then
    #     prompt_segment "$AGNOSTER_VENV_BG" "$AGNOSTER_VENV_FG" "(${VIRTUAL_ENV:t:gs/%/%%})"
    # fi
}

CONDA_CHANGEPS1=false

# Load shared bash-style files if you keep them
[[ -f "$HOME/.bash_aliases"   ]] && source "$HOME/.bash_aliases"
[[ -f "$HOME/.bash_functions" ]] && source "$HOME/.bash_functions"
[[ -f "$HOME/.bash_secrets"   ]] && source "$HOME/.bash_secrets"

# Conda (zsh hook)
if [[ -x "$HOME/miniconda3/bin/conda" ]]; then
    __conda_setup="$("$HOME/miniconda3/bin/conda" "shell.zsh" "hook" 2>/dev/null)"
    if [[ $? -eq 0 ]]; then
        eval "$__conda_setup"
    else
        [[ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]] && source "$HOME/miniconda3/etc/profile.d/conda.sh"
    fi
    unset __conda_setup
fi

# fzf
[[ -f "$HOME/.fzf.zsh" ]] && source "$HOME/.fzf.zsh"

# Utilities
r() {
    [[ -z "$1" ]] && { echo "usage: r <file>"; return 2; }
    realpath "$1"
}

# PATH (prefer your bin first)
export PATH="$HOME/bin:$PATH"

# VS Code environment (useful if remote shell breaks)
[[ -f "$HOME/.vscode_env.sh" ]] && source "$HOME/.vscode_env.sh"

# if [[ -n "$VSCODE_IPC_HOOK_CLI" ]]; then
#     cat > "$HOME/.vscode_env.sh" <<EOF
# # Generated by .zshrc when launched from VS Code
# if [ -z "\$VSCODE_IPC_HOOK_CLI" ]; then
#     export VSCODE_IPC_HOOK_CLI="$(printf '%q' "$VSCODE_IPC_HOOK_CLI")"
#     alias code="$(printf '%q' "${VSCODE_GIT_ASKPASS_NODE%/*}/bin/code")"
# fi
# EOF
# fi

# NVM
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"
[[ -s "$NVM_DIR/bash_completion" ]] && source "$NVM_DIR/bash_completion"